#!/usr/bin/env python3
"""Create a new IF Hub project with build, test, and web infrastructure.

Usage:
    python tools/new_project.py "Game Title" game-name [--engine ENGINE]

Supported engines: inform7 (default), ink, wwwbasic, qbjc, applesoft, twine.
Creates a complete project scaffold with source file, tests, CI, and CLAUDE.md.
"""

import argparse
import sys
import textwrap
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.paths import PROJECTS_DIR, I7_ROOT, new_project_dir
from lib.config import ENGINE_REGISTRY, get_engine_spec

# Engines available for project creation (subset of ENGINE_REGISTRY)
CREATABLE_ENGINES = ["inform7", "ink", "wwwbasic", "qbjc", "applesoft", "bwbasic", "jsdos", "twine"]


# ---------------------------------------------------------------------------
# Shared scaffolding (all engines)
# ---------------------------------------------------------------------------


def write_gitignore(project_dir, engine):
    """Write .gitignore appropriate for the engine."""
    lines = [
        "# Assembled site output (generated by build_site.py / CI)",
        "_site/",
        "",
        "# Pipeline state (generated by pipeline.py)",
        ".pipeline-state",
        "",
        "# Claude Code local settings",
        ".claude/",
        "",
        "# OS generated files",
        "$RECYCLE.BIN/",
        "[Dd]esktop.ini",
        ".DS_Store",
        "Thumbs.db",
        "*~",
        ".*.sw[op]",
        "",
        "# IDE",
        ".vscode/",
        ".idea/",
    ]
    if engine == "inform7":
        lines[1:1] = [
            "",
            "# Build output",
            "*.ulx",
            "*.i6",
            "*.materials/",
            "",
            "# Inform 7 IDE project wrappers",
            "*.inform/",
            "",
            "# Test output (generated)",
            "tests/inform7/walkthrough_output.txt",
        ]
    (project_dir / ".gitignore").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_deploy_workflow(project_dir):
    """Write GitHub Actions deploy-pages.yml."""
    (project_dir / ".github" / "workflows").mkdir(parents=True, exist_ok=True)
    (project_dir / ".github" / "workflows" / "deploy-pages.yml").write_text(
        textwrap.dedent("""\
        name: Deploy to GitHub Pages

        on:
          push:
            branches: [main]
          workflow_dispatch:

        permissions:
          contents: read
          pages: write
          id-token: write

        concurrency:
          group: pages
          cancel-in-progress: false

        jobs:
          deploy:
            environment:
              name: github-pages
              url: ${{ steps.deployment.outputs.page_url }}
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: actions/configure-pages@v5
              - name: Assemble site
                run: |
                  mkdir -p _site
                  [ -d web ] && cp -r web/* _site/ || true
                  [ -d lib ] && cp -r lib _site/ || true
                  cp *.html _site/ 2>/dev/null || true
                  cp *.txt _site/ 2>/dev/null || true
                  cp *.ni _site/ 2>/dev/null || true
                  cp *.ink _site/ 2>/dev/null || true
                  cp *.json _site/ 2>/dev/null || true
                  cp *.bas _site/ 2>/dev/null || true
              - uses: actions/upload-pages-artifact@v3
                with:
                  path: _site
              - id: deployment
                uses: actions/deploy-pages@v4
    """),
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Engine-specific scaffolding
# ---------------------------------------------------------------------------


def scaffold_inform7(project_dir, title, name):
    """Create an Inform 7 project scaffold."""
    (project_dir / "tests" / "inform7").mkdir(parents=True, exist_ok=True)
    _write_starter_walkthrough(project_dir)

    year = datetime.now().year

    # story.ni
    (project_dir / "story.ni").write_text(textwrap.dedent(f"""\
        "{title}" by "Johnesco"

        The story headline is "An Interactive Fiction".
        The story genre is "Fantasy".
        The release number is 1.
        The story creation year is {year}.
        The story description is "An interactive fiction game."

        Use American dialect.
        Use scoring.
        The maximum score is 1.

        Part 1 - Configuration

        When play begins:
        \tnow the left hand status line is "[the player's surroundings]   Score: [score]/[turn count]";
        \tnow the right hand status line is "";
        \tsay "[bold type]{title}[roman type][line break]An Interactive Fiction by Johnesco[paragraph break]".

        Part 2 - The World

        The Starting Room is a room. "You are in an empty room. This is where your game begins."
    """), encoding="utf-8")

    # tests/project.conf
    (project_dir / "tests" / "project.conf").write_text(textwrap.dedent(f"""\
        #!/bin/bash
        # {title} -- project-specific test configuration
        # Parsed by the testing framework (tools/testing/*.py)
        #
        # PROJECT_DIR is set by the framework before sourcing this file.

        # Project identity
        PROJECT_NAME="{title}"

        # Primary engine (Inform 7 / Glulx)
        PRIMARY_ENGINE_NAME="glulxe"
        PRIMARY_ENGINE_PATH="$HOME/glulxe/glulxe"
        PRIMARY_ENGINE_SEED_FLAG="--rngseed"
        PRIMARY_GAME_PATH="$PROJECT_DIR/{name}.ulx"
        PRIMARY_WALKTHROUGH="$PROJECT_DIR/tests/inform7/walkthrough.txt"
        PRIMARY_OUTPUT_FILE="$PROJECT_DIR/tests/inform7/walkthrough_output.txt"
        PRIMARY_SEEDS_KEY="glulxe"

        # Score extraction patterns (Inform 7 default output format)
        SCORE_REGEX='scored \\K[0-9]+'
        SCORE_FALLBACK_REGEX='[0-9]+(?= out of a possible [0-9]+)'
        MAX_SCORE_REGEX='possible \\K[0-9]+'
        PASS_THRESHOLD=1
        DEFAULT_MAX_SCORE=1

        # Diagnostic patterns
        DEATH_PATTERNS='you have died'
        WON_PATTERNS='You have won'

        # RegTest config
        REGTEST_FILE="$PROJECT_DIR/tests/{name}.regtest"
        REGTEST_ENGINE="$HOME/glulxe/glulxe"
        REGTEST_GAME="$PROJECT_DIR/{name}.ulx"

        # Pipeline config (used by tools/pipeline.py, ignored by testing framework)
        PIPELINE_SOUND=false
        PIPELINE_HUB_ID="{name}"
        PIPELINE_TESTS="walkthrough,regtest"
    """), encoding="utf-8")

    # seeds.conf
    (project_dir / "tests" / "seeds.conf").write_text(textwrap.dedent("""\
        # Golden seeds for deterministic walkthrough testing
        # Format: engine:seed:binary_hash:date
        # Re-discover with: python tools/testing/find_seeds.py --config tests/project.conf
        #
        # glulxe:TBD:TBD:TBD
    """), encoding="utf-8")

    # Starter regtest
    (project_dir / "tests" / f"{name}.regtest").write_text(textwrap.dedent(f"""\
        ** game: ../{name}.ulx
        ** interpreter: /home/johnesco/glulxe/glulxe -q

        * smoke
        > look
        Starting Room
    """), encoding="utf-8")

    # Starter walkthrough
    (project_dir / "tests" / "inform7" / "walkthrough.txt").write_text(
        "look\n", encoding="utf-8"
    )

    # CLAUDE.md
    (project_dir / "CLAUDE.md").write_text(textwrap.dedent(f"""\
        # {title}

        An Inform 7 interactive fiction.

        For build, test, and publish workflows, see `C:\\code\\ifhub\\reference\\project-guide.md`.
    """), encoding="utf-8")

    return "story.ni"


def _write_starter_walkthrough(project_dir):
    """Write a starter walkthrough.txt for any engine."""
    wt_path = project_dir / "tests" / "walkthrough.txt"
    if not wt_path.exists():
        wt_path.write_text("look\n", encoding="utf-8")


def scaffold_ink(project_dir, title, name):
    """Create an Ink project scaffold."""
    (project_dir / "tests").mkdir(parents=True, exist_ok=True)
    _write_starter_walkthrough(project_dir)

    # Source .ink file
    source_name = name.replace("-", "_") + ".ink"
    (project_dir / source_name).write_text(textwrap.dedent(f"""\
        // {title}
        // An interactive fiction by Johnesco

        === start ===
        You stand at a crossroads. The wind rustles through the trees.

        + [Go north] -> north_path
        + [Go south] -> south_path

        === north_path ===
        You walk north along a winding trail.

        + [Continue] -> ending
        + [Turn back] -> start

        === south_path ===
        You head south toward the sound of running water.

        + [Continue] -> ending
        + [Turn back] -> start

        === ending ===
        Your journey comes to an end. Thank you for playing.

        -> END
    """), encoding="utf-8")

    # tests/project.conf
    (project_dir / "tests" / "project.conf").write_text(textwrap.dedent(f"""\
        # {title} -- project configuration
        PROJECT_NAME="{title}"
        ENGINE=ink
        SOURCE={source_name}
        PIPELINE_SOUND=false
        PIPELINE_HUB_ID="{name}"
        PIPELINE_TESTS=""
    """), encoding="utf-8")

    # CLAUDE.md
    (project_dir / "CLAUDE.md").write_text(textwrap.dedent(f"""\
        # {title}

        An Ink interactive fiction.

        For build, test, and publish workflows, see `C:\\code\\ifhub\\reference\\project-guide.md`.
    """), encoding="utf-8")

    return source_name


def scaffold_basic(project_dir, title, name, engine):
    """Create a BASIC project scaffold (wwwbasic, qbjc, applesoft)."""
    (project_dir / "tests").mkdir(parents=True, exist_ok=True)
    _write_starter_walkthrough(project_dir)

    spec = get_engine_spec(engine)
    label = spec.label if spec else engine

    # Source .bas file
    source_name = name.replace("-", "_") + ".bas"
    (project_dir / source_name).write_text(textwrap.dedent(f"""\
        10 REM {title}
        20 REM An interactive fiction by Johnesco
        30 PRINT "{title}"
        40 PRINT "An Interactive Fiction"
        50 PRINT
        60 PRINT "You stand in an empty room."
        70 PRINT "Type QUIT to exit."
        80 PRINT
        90 INPUT "> ", A$
        100 IF A$ = "QUIT" OR A$ = "quit" THEN END
        110 PRINT "Nothing happens."
        120 GOTO 80
    """), encoding="utf-8")

    # tests/project.conf
    (project_dir / "tests" / "project.conf").write_text(textwrap.dedent(f"""\
        # {title} -- project configuration
        PROJECT_NAME="{title}"
        ENGINE={engine}
        SOURCE={source_name}
        PIPELINE_SOUND=false
        PIPELINE_HUB_ID="{name}"
        PIPELINE_TESTS=""
    """), encoding="utf-8")

    # CLAUDE.md
    (project_dir / "CLAUDE.md").write_text(textwrap.dedent(f"""\
        # {title}

        A {label} interactive fiction.

        For build, test, and publish workflows, see `C:\\code\\ifhub\\reference\\project-guide.md`.
    """), encoding="utf-8")

    return source_name


def scaffold_twine(project_dir, title, name):
    """Create a Twine project scaffold."""
    (project_dir / "tests").mkdir(parents=True, exist_ok=True)
    _write_starter_walkthrough(project_dir)

    # Source .tw file (Twee notation)
    source_name = name.replace("-", "_") + ".tw"
    (project_dir / source_name).write_text(textwrap.dedent(f"""\
        :: StoryTitle
        {title}

        :: StoryData
        {{
          "ifid": "",
          "format": "Harlowe",
          "format-version": "3.3.9"
        }}

        :: Start
        You stand at a crossroads.

        [[Go north->North Path]]
        [[Go south->South Path]]

        :: North Path
        You walk north along a winding trail.

        [[Continue->Ending]]
        [[Turn back->Start]]

        :: South Path
        You head south toward the sound of running water.

        [[Continue->Ending]]
        [[Turn back->Start]]

        :: Ending
        Your journey comes to an end. Thank you for playing.
    """), encoding="utf-8")

    # tests/project.conf
    (project_dir / "tests" / "project.conf").write_text(textwrap.dedent(f"""\
        # {title} -- project configuration
        PROJECT_NAME="{title}"
        ENGINE=twine
        SOURCE={source_name}
        PIPELINE_SOUND=false
        PIPELINE_HUB_ID="{name}"
        PIPELINE_TESTS=""
    """), encoding="utf-8")

    # CLAUDE.md
    (project_dir / "CLAUDE.md").write_text(textwrap.dedent(f"""\
        # {title}

        A Twine interactive fiction.

        For build, test, and publish workflows, see `C:\\code\\ifhub\\reference\\project-guide.md`.
    """), encoding="utf-8")

    return source_name


def scaffold_jsdos(project_dir, title, name):
    """Create a DOS (js-dos) project scaffold."""
    (project_dir / "tests").mkdir(parents=True, exist_ok=True)

    # Placeholder — user must provide their own .jsdos bundle
    source_name = name.replace("-", "_") + ".jsdos"

    # tests/project.conf
    (project_dir / "tests" / "project.conf").write_text(textwrap.dedent(f"""\
        # {title} -- project configuration
        PROJECT_NAME="{title}"
        ENGINE=jsdos
        SOURCE={source_name}
        PIPELINE_SOUND=false
        PIPELINE_HUB_ID="{name}"
        PIPELINE_TESTS=""
    """), encoding="utf-8")

    # CLAUDE.md
    (project_dir / "CLAUDE.md").write_text(textwrap.dedent(f"""\
        # {title}

        A DOS game (js-dos).

        For build, test, and publish workflows, see `C:\\code\\ifhub\\reference\\project-guide.md`.
    """), encoding="utf-8")

    return source_name


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="Create a new IF Hub project.")
    parser.add_argument("title", help="Game title (quoted)")
    parser.add_argument("name", help="Project directory name (lowercase)")
    parser.add_argument("--engine", default="inform7",
                        choices=CREATABLE_ENGINES,
                        help="Engine type (default: inform7)")
    args = parser.parse_args()

    title = args.title
    name = args.name
    engine = args.engine
    project_dir = new_project_dir(engine, name)

    if project_dir.is_dir():
        print(f"ERROR: Directory already exists: {project_dir}", file=sys.stderr)
        sys.exit(1)

    spec = get_engine_spec(engine)
    label = spec.label if spec else engine

    print(f"Creating project: {title} ({name}) [{label}]")
    print(f"  Location: {project_dir}")
    print()

    # Create base directories
    project_dir.mkdir(parents=True, exist_ok=True)

    # Engine-specific scaffold
    if engine == "inform7":
        source_file = scaffold_inform7(project_dir, title, name)
    elif engine == "ink":
        source_file = scaffold_ink(project_dir, title, name)
    elif engine in ("wwwbasic", "qbjc", "applesoft", "bwbasic"):
        source_file = scaffold_basic(project_dir, title, name, engine)
    elif engine == "jsdos":
        source_file = scaffold_jsdos(project_dir, title, name)
    elif engine == "twine":
        source_file = scaffold_twine(project_dir, title, name)
    else:
        print(f"ERROR: Unsupported engine: {engine}", file=sys.stderr)
        sys.exit(1)

    # Shared files
    write_gitignore(project_dir, engine)
    write_deploy_workflow(project_dir)

    # Add to games-registry.json so the dashboard can find it
    from lib.paths import GAMES_REGISTRY, GH_ORG, engine_dir_key
    import json
    try:
        registry = json.loads(GAMES_REGISTRY.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        registry = {}
    registry[name] = {
        "path": f"../text-games/{engine_dir_key(engine)}/{name}",
        "repo": f"{GH_ORG}/{name}",
    }
    GAMES_REGISTRY.write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")

    print()
    print(f"Project created at: {project_dir}")
    print(f"  Added to games-registry.json")
    print()
    print("Next steps:")
    print(f"  1. Edit {project_dir / source_file}")
    print(f"  2. Build:    python {I7_ROOT / 'tools' / 'build.py'} {name}")
    print(f"  3. Publish:  python C:/code/ifhub/tools/ship.py {name}")


if __name__ == "__main__":
    main()
